// Generate the Pikafish-verified solution book for every puzzle.
// For each winning puzzle we BFS the solution tree: red plays Pikafish's best
// move, and we expand EVERY black reply (dedup by position) so the hint has a
// correct move for any position the player can reach.
//
// Usage: PIKAFISH_BIN=... PIKAFISH_DIR=... node --experimental-strip-types tools/solve.mjs
import { writeFileSync } from 'node:fs';
import { ENDGAMES } from '../src/data/endgames.ts';
import { parseFen, applyMove, getAllLegalMoves, boardToFen } from '../src/engine/board.ts';
import { appToUciFen, uciMoveToApp } from './lib/fen.mjs';
import { createEngine } from './lib/uci.mjs';

const MOVETIME = 200;   // ms per red node — plenty for these endgames
const NODE_CAP = 1200;  // max red-to-move nodes stored per puzzle

const eng = createEngine();
await eng.init({ Threads: 4, Hash: 256 });

/** @type {Record<string,string>} */
const solutions = {};
const report = [];

for (const e of ENDGAMES) {
  const root = parseFen(e.fen);
  const chk = await eng.analyse(appToUciFen(e.fen, 'red'), { movetime: 1000 });
  if (!(chk.scoreType === 'mate' && chk.score > 0)) {
    report.push(`${e.id} ${e.title}: ⚠️跳过（非红胜: ${chk.scoreType} ${chk.score}）`);
    continue;
  }

  const visited = new Set();
  const queue = [root];
  let covered = 0;
  while (queue.length && covered < NODE_CAP) {
    const board = queue.shift();
    const key = boardToFen(board);
    if (visited.has(key)) continue;
    visited.add(key);

    const r = await eng.analyse(appToUciFen(key, 'red'), { movetime: MOVETIME });
    const mv = uciMoveToApp(r.move);
    solutions[key] = `${mv.from.row}${mv.from.col}${mv.to.row}${mv.to.col}`;
    covered++;

    const afterRed = applyMove(board, mv);
    const blackMoves = getAllLegalMoves(afterRed, 'black');
    for (const bm of blackMoves) {
      const afterBlack = applyMove(afterRed, bm);
      if (getAllLegalMoves(afterBlack, 'red').length === 0) continue; // red has no move (shouldn't happen)
      if (!visited.has(boardToFen(afterBlack))) queue.push(afterBlack);
    }
  }
  report.push(`${e.id} ${e.title}: 杀${chk.score}步, 收录 ${covered} 局面${queue.length ? ' ⚠️截断' : ' ✓完整'}`);
}
eng.quit();

const entries = Object.entries(solutions).map(([k, v]) => `  '${k}': '${v}',`).join('\n');
writeFileSync('src/data/solutions.ts',
  `// AUTO-GENERATED by tools/solve.mjs — do not edit by hand.\n` +
  `// Pikafish-verified winning moves. key = app board FEN (red to move),\n` +
  `// value = "frFcTrTc" = from(row,col) to(row,col).\n` +
  `export const SOLUTIONS: Record<string, string> = {\n${entries}\n};\n`);

console.log('\n' + report.join('\n'));
console.log(`\n总收录局面: ${Object.keys(solutions).length}`);
